version: '3.8'

services:
  server:
    build: 
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
  
  client:
    build: 
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
