name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_WFS_API_URL: ${{ secrets.REACT_APP_WFS_API_URL }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd client
        npm install
    - name: Run Unit Tests
      run: |
        cd client
        npm test
